name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Copiar testData.example.json para testData.json (se não existir)
        run: |
          if [ ! -f cypress/fixtures/testData.json ]; then
            cp cypress/fixtures/testData.example.json cypress/fixtures/testData.json
          fi

      - name: Run Cypress tests
        run: npx cypress run
